- src/ngamsPlugIns/ngamsPlugIns/mwa/ngamsMWAOnlinePlugIn.py
- src/ngamsPlugIns/ngamsPlugIns/ngamsGenericOnlinePlugIn.py
This adds an additional logging statement to specify which file is being looked for, and corrects two bits of documentation. This is based on master, rather than v11 (like #4 was).
> Clarify volume checking (on top of master)

- .gitignore
- tox.ini
[Tox](https://tox.readthedocs.io/en/latest/) is virtualenv manager for test - it installs the requirements, the package to test, and runs the tests within a virtualenv (creating a new venv for each python version). This adds a simple one (so that I don't need to remember to run build.sh every time I want to run the tests or remeber to install psutil in every venv ;)), but it's fairly easy to add features if need be (see https://github.com/h5py/h5py/blob/master/tox.ini for some of the power tox gives to control the test environment).
> Add simple tox config

- .travis/run_tests.sh
- src/ngamsCore/ngamsLib/ngamsHttpUtils.py
- src/ngamsCore/ngamsLib/ngamsStatus.py
- src/ngamsCore/ngamsLib/ngamsSubscriber.py
- src/ngamsCore/ngamsLib/pysendfile.py
- src/ngamsCore/setup.py
- src/ngamsPClient/ngamsPClient/ngamsPClient.py
- src/ngamsServer/ngamsServer/janitor/rotated_logfiles_handler.py
- src/ngamsServer/ngamsServer/ngamsServer.py
- src/ngamsServer/ngamsServer/ngamsSubscriptionThread.py
- test/client/test_python_client.py
- test/ngamsTestLib.py
- test/test_subscription.py
- tox.ini
This adds some HTTPS support to NGAS. The main changes are whether sendfile is used (it's possible to use sendfile with https, but you need a recent linux kernel, very new openssl etc., so it makes sense to wait until that has stabilised before trying to add that), and using urls where possible to keep around the protocols. Let me know if there are any issues with this (I don't think there are any breaking changes.
Closes #8.
> Add https to core system

- cfg/sample_server_config.xml
- doc/changelog.rst
- doc/configuration.rst
- src/ngamsCore/ngamsLib/ngamsConfig.py
- src/ngamsPlugIns/ngamsPlugIns/ngas_sub_auth_plugin.py
- src/ngamsServer/ngamsServer/ngamsSubscriptionThread.py
- test/support/subscription_auth_plugin.py
- test/test_subscription.py
Building on #8, this allows services which use the requests code path (so currently just https) to be able to specify which authentication to use for a connection when subscribing. The test uses BasicAuth, but any requests authentication plugin will work (DC is planning on using JWT, as mention in #9), as long as they can be used with the auth argument (OAUTH2 requires a bigger setup, but I doubt that people are going to use it with ngas...). Let me know if this seems reasonable.  
This also adds an [editorconfig](https://editorconfig.org/) file so that hopefully no matter what editor people use, the formatting should be the same (I can drop this from the PR if you'd prefer).
> Allow subscription to use authentication plugins

- src/ngamsCore/ngamsLib/ngamsHttpUtils.py
We ended up using TLS client certificates to do authentication at DC, this patch allows specifying the client certificate via environment variables.
This is mainly a workaround for https://github.com/psf/requests/issues/5255 (which will hopefully be fixed soon), so ideally this would be handled in the future by #15.
> Allow NGAS to use client certificates via NGAS_CLIENT_*

- src/ngamsServer/ngamsServer/ngamsSubscriptionThread.py
It looks like if the first delivery fails due to an exception (in our case a certificate problem, but any exception will do), `lastDelivery` can be `None` where `lastSchedule` isn't. This adds one more check to the if statement to cover that case.
> Fix bugs where lastDelivery is None in comparison

- src/ngamsPClient/ngamsPClient/ngamsPClient.py
- test/client/test_python_client.py
This set of changes improves the `-s` command line argument to take an optional file name. This has the effect of dumping the XML status document into that file instead of into `stdout`, which is still the behavior when `-s` is passed without a value.
There are also some other minor improvements, including unit testing of the new functionality and of the `--license` and `--version` command-line switches.
> Python client improvements

- src/ngamsServer/ngamsServer/janitor/rotated_logfiles_handler.py
Before logfiles are rotated (i.e., removed) a series of processing tasks are performed onto them. Among these, the first one is to archive the logfile into the NGAS server itself, if the server has been configured for this. During normal operations this is not a problem, but exactly on the first try, when the janitor process has just been created and the HTTP server might not be bound yet, it might result on an ECONNREFUSED error. This produced big error messages on the logs, while in reality this is a transient error that should disappear on the next try.
A second, more general problem, was found while inspecting this code: logfiles were not renamed back to have their original ".unsaved" extensions when errors happened. This meant that when errors in general were found (and in particular …
> Deal correctly with errors when archiving logfiles

- src/ngamsServer/ngamsServer/commands/retrieve.py
- src/ngamsServer/ngamsServer/commands/status.py
- src/ngamsServer/ngamsServer/ngamsFileUtils.py
- src/ngamsServer/ngamsServer/ngamsServer.py
- test/commands/test_archive.py
- test/ngamsTestLib.py
- test/test_config_handling.py
- test/test_db.py
- test/test_partner_sites.py
This is the partner sites feature that was developed and used by the ALMA observatory. It is very useful and important feature for every day ALMA use in development and testing. It is also useful in production.
I cleaned up the code and refactored it so it is much cleaner than it was on the older NGAS code base. Please let me know if there are any further improvements I can make.
Update:
I forgot to say that the partner site feature is enabled in the NGAS XML configuration by adding the following element...
```
<PartnerSites ProxyMode="1">
<PartnerSite Address="http://ngas01.example.com:8080"/>
</PartnerSites>
```
> Ported partner sites feature from ALMA NGAS source code

- doc/changelog.rst
- doc/configuration.rst
- src/ngamsCore/ngamsLib/ngamsConfig.py
- src/ngamsServer/ngamsServer/ngamsAuthUtils.py
- test/test_authorization.py
This feature would be useful for ALMA as we have lots of existing software interfacing with NGAS. It would difficult adding support for authorization to all of them all in one go. This feature would allow us to improve security gradually.
Oh, and this time I made sure I added a unit test :)
> Added exclude commands feature to authorization

- doc/changelog.rst
- doc/configuration.rst
- src/ngamsServer/ngamsServer/ngamsFileUtils.py
- src/ngamsServer/ngamsServer/ngamsServer.py
- test/test_partner_sites.py
There was a bug in the partner sites feature. It was largely down to a misunderstanding on my part. I thought the partner site server should act as a proxy but instead we should stream the file directly from where it is hosted.
I also added a new function to parse the host ID. Perhaps one already exists. If so I can remove it and reuse the existing function.
> Fixed redirect bug in partner sites

- src/ngamsServer/ngamsServer/ngamsServer.py
- test/test_partner_sites.py
After some tests we found that the range requests was broken. It would appear that we do not need to calculate the start byte (offset) when resuming a retrieve request. I have updated the unit tests to handle this scenario.
> Partner sites

- src/ngamsCore/ngamsSql/ngamsCreateTables-Oracle.sql
- src/ngamsServer/ngamsServer/ngamsSrvUtils.py
I removed a primary key from the Oracle SQL script. This should never have been included. I saw it on the old code base and thought it was probably a good thing. It was a bad choice on my part.
I fixed the subscribe ID bug. A trivial change. The unit tests pass OK. I was tempted to do more but I thought it best to stop there.
> Fix subscription from config

- src/ngamsPlugIns/ngamsPlugIns/alma/ngamsAlmaMultipart.py
- src/ngamsPlugIns/ngamsPlugIns/ngamsCmd_HTTPFETCH.py
- src/ngamsPlugIns/ngamsPlugIns/ngamsCmd_MIRRARCHIVE.py
- src/ngamsPlugIns/ngamsPlugIns/ngamsCmd_MIRREXEC.py
- src/ngamsPlugIns/ngamsPlugIns/ngamsCmd_MIRRTABLE.py
- src/ngamsPlugIns/ngamsPlugIns/ngamsCmd_RSYNCFETCH.py
- src/ngamsPlugIns/ngamsPlugIns/ngamsDAPIMirroring.py
- src/ngamsPlugIns/ngamsPlugIns/ngamsSdmMultipart.py
- src/ngamsServer/ngamsServer/ngamsMirroringControlThread.py
- src/ngamsServer/ngamsServer/ngamsServer.py
- test/plugins/test_dapi_mirroring.py
I was working on the mirroring plugin. I decided to clean up some of the code by applying PEP8 style guidelines. I also fixed a couple of bugs. You can follow the changes in the commit log.
Sadly there are still no unit tests for mirroring because it is just too complicated. I would need to create two clusters with two database schemas with a database link between the schemas. This is not achievable with sqlite. The alternative would be to mock the methods but this would require a significant amount of work and I don't have the time to do this at the moment.
> Mirroring plugin code cleanup

- src/ngamsPlugIns/ngamsPlugIns/ngamsSdmMultipart.py
A small bug fix. I forgot to test this change properly before committing. Now I have a CI pipeline I can setup more tests to catch these type of bugs in the future.
> Fix file_version bug in ngamsSdmMultipart plugin

- src/ngamsServer/ngamsServer/commands/retrieve.py
- src/ngamsServer/ngamsServer/ngamsFileUtils.py
- src/ngamsServer/ngamsServer/ngamsServer.py
- test/test_partner_sites.py
This is a quick fix but I think the `retrieve._handleCmdRetrieve()` function needs some further improvements. There are a few of issues:
1. The NGAS host ID may include the port value (e.g. `ngas01:7777`). There are few places in the code where we construct a URL (e.g. `host + ':' + port + '/' + command + ...`). This will often result in the URL `ngas01:7777:7777/RETRIEVE?...`. Somehow this still works most of the time in python 2 but the `urlparse` module in python 3 fails to parse the URL and throws an exception.
2. I think the `ngamsFileUtils.quickFileLocate()` function should really return a `NGAMS_HOST_CLUSTER` instead of `NGAMS_HOST_REMOTE` value. This makes more sense to me. Presently if the file is available in another node in the cluster it will end up being retrieved by the …
> Fix retrieve command issues

- src/ngamsPlugIns/ngamsPlugIns/ngamsCmd_MIRREXEC.py
In python 3 the `response.read` attribute is now binary. We convert it to a string to check the status.
> Convert response body to a string when checking contents

- src/ngamsPlugIns/ngamsPlugIns/ngamsCmd_MIRRTABLE.py
Oracle-specific code for ALMA-specific mirroring => no automated tests.
The problem we had was that when we had a lot of files to mirror, and we had limited the number of files we would mirror in each iteration, it was possible that a file which failed to mirror in one iteration, would be not be re-attempted until a much later iteration. This was because of the way in which we removed files from the mirroring table. 
Everything worked as expected, but it confused testers.
> added determinism when testing mirroring with iteration file limits

- src/ngamsServer/ngamsServer/ngamsMirroringControlThread.py
- src/ngamsServer/ngamsServer/ngamsServer.py
Not a nice solution in the end. In our old NGAS version we used to not care about non-alma mirroring so the mirroring thread always started, executed cleanup, and exited.
Anyway, this fixes many issues we were seeing with servers bring stopped / started / killed.
> allow alma mirroring to always clean up at the start

- src/ngamsPlugIns/ngamsPlugIns/alma/ngamsAlmaMultipart.py
- src/ngamsPlugIns/ngamsPlugIns/ngamsCmd_HTTPFETCH.py
- src/ngamsPlugIns/ngamsPlugIns/ngamsDAPIMirroring.py
- src/ngamsPlugIns/ngamsPlugIns/ngamsRegisterAlmaPlugIn.py
- src/ngamsPlugIns/ngamsPlugIns/ngamsSdmMultipart.py
When I ported the old code from using the rc822 module to using the email instead I did not realise that I had introduced a new problem. The old rf822 module was very memory efficient where as the new email modules appears to read the entire file contents into memory. I have written a simple file parer that only pareses the MIME file primary header unit. This is all we need for ALMA when trying to determine if the file is a `multipart/mixed` or `multipart/related`.
> Email file memory fix

- src/ngamsServer/ngamsServer/ngamsFileUtils.py
We only want to convert '/' to '_' for the file_id and not the whole path.
> Fixed 'check file' command bug

- src/ngamsPlugIns/ngamsPlugIns/ngamsCmd_MIRRTABLE.py
preventing them from being mirrored in future iterations.
> remove a rare case where files can be stuck in READY status

- src/ngamsServer/setup.py
Since we are still supporting not only old versions of python, but also old versions of setuptools, we can't rely on PEP-508 dependency specifications being supported. These were added around 2016 in setuptools version 20, while RHEL7 comes with 0.9.8, thus not supporting this format
> Use traditional version constraining method
